default: &default
  adapter: mysql2
  port: 3306
  host: 127.0.0.1
  database: tripthru
  pool: 5
  timeout: 5000
  username: vagrant
  password: vagrant
#
development:
  <<: *default
  username: tripservice
  password: Tr1PServ1CeMySqL
  host: tripthru.cegl4aakuq4b.us-west-2.rds.amazonaws.com

production:
  <<: *default
  username: tripservice
  password: Tr1PServ1CeMySqL
  host: tripthru.cegl4aakuq4b.us-west-2.rds.amazonaws.com
  database: tripthru