default: &default
  adapter: mysql2
  port: 3306
  host: 127.0.0.1
  database: tripthru
  pool: 5
  timeout: 5000
#
development:
  <<: *default
  username: tripuser
  password: Tr1PServ1Ce@MySqL
  host: 107.170.235.36

production:
  <<: *default
  username: tripuser
  password: Tr1PServ1Ce@MySqL
  host: 107.170.235.36
  database: tripthru